import jsPDF from 'jspdf';

export const exportBreadsToPDF = async (breads, username) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = margin;

  // Title
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`${username}'s Bread Journal`, margin, yPos);
  yPos += 15;

  // Date range
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  const exportDate = new Date().toLocaleDateString();
  pdf.text(`Exported on ${exportDate}`, margin, yPos);
  yPos += 10;

  // Summary
  pdf.setFontSize(12);
  pdf.text(`Total Breads: ${breads.length}`, margin, yPos);
  yPos += 15;

  // Breads
  for (let i = 0; i < breads.length; i++) {
    const bread = breads[i];

    // Check if we need a new page
    if (yPos > pageHeight - 60) {
      pdf.addPage();
      yPos = margin;
    }

    // Bread separator line
    pdf.setDrawColor(139, 69, 19); // Brown color
    pdf.setLineWidth(0.5);
    pdf.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 10;

    // Bread name
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text(bread.name, margin, yPos);
    yPos += 8;

    // Type and date
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    if (bread.bread_type) {
      pdf.text(`Type: ${bread.bread_type}`, margin, yPos);
      yPos += 6;
    }
    pdf.text(`Baked: ${new Date(bread.bake_date).toLocaleDateString()}`, margin, yPos);
    yPos += 8;

    // Ratings
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Ratings:', margin, yPos);
    yPos += 6;

    pdf.setFont('helvetica', 'normal');
    const ratings = [
      { label: 'Crust', value: bread.crust_rating },
      { label: 'Crumb', value: bread.crumb_rating },
      { label: 'Taste', value: bread.taste_rating },
      { label: 'Texture', value: bread.texture_rating },
      { label: 'Appearance', value: bread.appearance_rating }
    ].filter(r => r.value);

    // Calculate average
    const avgRating = ratings.length > 0
      ? (ratings.reduce((sum, r) => sum + r.value, 0) / ratings.length).toFixed(1)
      : 'N/A';

    ratings.forEach(({ label, value }) => {
      pdf.text(`  ${label}: ${value}/10`, margin + 5, yPos);
      yPos += 5;
    });

    pdf.setFont('helvetica', 'bold');
    pdf.text(`  Average: ${avgRating}/10`, margin + 5, yPos);
    yPos += 8;

    // Notes
    if (bread.notes) {
      pdf.setFont('helvetica', 'bold');
      pdf.text('Notes:', margin, yPos);
      yPos += 6;
      pdf.setFont('helvetica', 'normal');
      const notesLines = pdf.splitTextToSize(bread.notes, contentWidth - 10);
      pdf.text(notesLines, margin + 5, yPos);
      yPos += notesLines.length * 5 + 3;
    }

    // Recipe notes
    if (bread.recipe_notes) {
      pdf.setFont('helvetica', 'bold');
      pdf.text('Recipe Notes:', margin, yPos);
      yPos += 6;
      pdf.setFont('helvetica', 'normal');
      const recipeLines = pdf.splitTextToSize(bread.recipe_notes, contentWidth - 10);
      pdf.text(recipeLines, margin + 5, yPos);
      yPos += recipeLines.length * 5 + 3;
    }

    yPos += 10;
  }

  // Footer on last page
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'italic');
  pdf.text('Generated by Bread Journal', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save the PDF
  const filename = `${username.replace(/\s+/g, '_')}_bread_journal_${new Date().getTime()}.pdf`;
  pdf.save(filename);
};
